Feat/trt docker
osai-ai/dokai pull request #6
Opened 2022-08-25 13:45 UTC by ivashnyov

Docker image with tensorrt library is added

2022-08-25 13:53 UTC, sankovalev requested changes
Please update readme for the last version of dokai

2022-08-25 13:53 UTC, sankovalev commented on Makefile
> +build-tensor-stream:
Wrong name of target

2022-08-25 13:53 UTC, sankovalev commented on docker/Dockerfile.tensorrt
> +    nvidia-tensorrt==8.2.3
One extra line is needed at the end of file

2022-08-25 13:56 UTC, smivv commented on Makefile
> +build-tensor-stream:
косяк

2022-08-25 13:56 UTC, smivv commented on docker/Dockerfile.tensorrt
> +FROM dokai:pytorch
почему не от тензорстрима?

2022-08-25 13:56 UTC, smivv commented on docker/Dockerfile.tensorrt
> +    nvidia-tensorrt==8.2.3
пустая строка

2022-08-25 14:49 UTC, ivashnyov commented on docker/Dockerfile.tensorrt
> +FROM dokai:pytorch
Потому что в opm не от тензорстрима. С Сашей решили, что его можно накатить сверху отдельно, если будет нужно

2022-08-25 14:53 UTC, sankovalev commented on docker/Dockerfile.tensorrt
> +FROM dokai:pytorch
И тензорстрим может блочить будущие релизы

2022-08-25 17:11 UTC, smivv commented on docker/Dockerfile.tensorrt
> +FROM dokai:pytorch
тогда предлагаю ещё один образ в котором и тензорстрим и трт

что думаете?

я правда предполагаю что при установке opm все равно будут ставиться все кудовские либы(

2022-08-27 10:14 UTC, sankovalev approved these changes

2022-08-27 10:25 UTC, merged